spring:

  config:
    #optional: .env 파일이 없어도 컴파일 에러가 발생 X
    #file: 파일을 import하겠다
    #.env: 파일명
    import: optional:file:.env
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: ${DEFAULT.DB_URL}
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: ${DEFAULT.DB_USERNAME}
    password: ${DEFAULT.DB_PASSWORD}
  servlet:
    multipart:
      max-file-size: 5MB
  jackson:
    deserialization:
      fail-on-unknown-properties: false
  data:
    redis:
      port: ${DEFAULT.REDIS.PORT}
      host: ${DEFAULT.REDIS.HOST}
  mail:
    username: ${MAIL.USERNAME}
    password: ${MAIL.PASSWORD}


mybatis:
  mapper-locations: mappers/**/*.xml

springdoc:
  api-docs:
    version: openapi_3_1
  swagger-ui:
    path: /swagger
    operations-sorter: method
    default-model-expand-depth: 10
  cache:
    disabled: true

file:
  dir: ${DEFAULT.FILE_DIRECTORY}

app:
  jwt:
    secret: ${JWT_SECRET}

    header-schema-name: authorization

    token-type: Bearer

    access-token-expiry: 3_600_000

    refresh-token-expiry: 1_296_000_000

---

spring:
  config:
    activate:
      on-profile: tdd
  datasource:
    url: ${TDD.DB_URL}
  sql:
    init:
      mode: always
logging:
  directory: ${DEFAULT.FILE_DIRECTORY}

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${PROD.DB.URL}
    username: ${PROD.DB.USERNAME}
    password: ${PROD.DB.PASSWORD}
  data:
    redis:
      port: ${PROD.REDIS.PORT}
      host: ${PROD.REDIS.HOST}
  mail:
    username: ${MAIL.USERNAME}
    password: ${MAIL.PASSWORD}

server:
  port: ${PROD.SSL.SERVER.PORT}
  ssl:
    key-store: ${PROD.SSL.KEY.STORE}
    key-store-password: ${PROD.SSL.PASSWORD}
    key-password: ${PROD.SSL.PASSWORD}

file:
  directory: ${PROD.FILE.DIRECTORY}

