spring:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: jdbc:log4jdbc:mariadb://192.168.0.19:3306/baedalyo
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: root
    password: green502
  servlet:
    multipart:
      max-file-size: 5MB

mybatis:
  mapper-locations: mappers/**/*.xml

springdoc:
  api-docs:
    version: openapi_3_1
  swagger-ui:
    path: /swagger
    operations-sorter: method
    default-model-expand-depth: 10
  cache:
    disabled: true

file:
  dir: D:\youp\download\baedalyo\

app:
  jwt:
    secret: DaeguGreenArtAcademy3rdTeamJavaSpringBootSecondProjectAF423DF1SD51FEWGREENQWT12QWQ4561

    header-schema-name: authorization

    token-type: Bearer

    access-token-expiry: 60_000

    refresh-token-expiry: 1_296_000_000

---

spring:
  config:
    activate:
      on-profile: tdd
  datasource:
    url: jdbc:log4jdbc:mariadb://localhost:3306/baedalyo_tdd
  sql:
    init:
      mode: always


logging:
  directory: D:\youp\download\baedalyo\

